events {
    worker_connections 1024;
}

http {
    # Máximo absoluto: 1 petición por segundo por IP
    limit_req_zone $binary_remote_addr zone=limite_reservas:10m rate=1r/s;

    server {
        listen 80;

        location /reservas/ {
            # CERO tolerancia (sin ráfagas). Si mandas 2 de golpe, mueres.
            limit_req zone=limite_reservas nodelay;
            limit_req_status 429; 

            proxy_pass http://reservas-service:5001/reservas/;
        }
    }
}